name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  backend:
    name: Build & Test Spring Boot
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build backend
      run: |
        cd spring-boot-mini-rn
        ./mvnw clean install
        ./mvnw test

  mobile:
    name: Install & Test Expo App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache
        restore-keys: |
          ${{ runner.os }}-npm

    - name: Install dependencies
      run: |
        cd mini-project-rn
        npm install

    - name: Install Maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash

    - name: Run Maestro tests
      run: |
        export PATH="$PATH:$HOME/.maestro/bin"
        cd mini-project-rn
        maestro test maestro/maestro_test.yaml
